### ISSUE TITLE
Monolingual Corpora provided are tokenized?

### ISSUE THREAD

**Issue by jerinphilip** [AI4Bharat/indicnlp_corpus#6]
Is there an untokenized version? I get a feeling that the corpora is tokenized with indicnlp library, space-separating punctuations?

```
$ head ml.txt
മകനു വേണ്ടി അച്ഛനും പ്രമുഖ നിർമ്മാതാവുമായ എ എൽ അളഗപ്പനാണ് വിവാഹം നടത്താൻ തീരുമാനിച്ചിരിക്കുന്നത് എന്നാണ് സൂചന .
ഇന്ന് റായ്ബറേലിയിൽ കോൺഗ്രസ് ഉപാദ്ധ്യക്ഷൻ രാഹുൽഗാന്ധിയുടെ രണ്ട് റാലികളിൽ പ്രിയങ്കഗാന്ധിയും പങ്കെടുക്കും .
എന്നാൽ രണ്ടു മാസത്തിനകം ഭരണഘടനാ കോടതി അദ്ദേഹത്തെ പ്രസിഡൻറ് പദത്തിൽ വീണ്ടും അവരോധിച്ചു .
വിവോ ഇന്ത്യ പ്രീമിയർ ലീഗിൽ ഔദ്യോഗിക പാർട്ണറായിരുന്നു ടാറ്റാ നെക്സോൺ .
വലിയൊരു സ്വപ്നം പൊലിഞ്ഞതിൽ സങ്കടമൊക്കെയുണ്ടായെങ്കിലും അത് മുഹമ്മദ് താലിഫ് എന്ന പന്ത്രണ്ടുകാരനെ പ്രസിദ്ധനാക്കിയിരിക്കുകയാണ് .
ഏറെ നാളത്തെ പ്രണയത്തിന് ശേഷമാണ് മലയാളികളുടെ പ്രിയ നടി ഭാവനയും കന്നഡ സിനിമാ നിർമാതാവ് നവീനും വിവാഹിതരാകാൻ പോകുന്നത് .
മൂന്നാം വിക്കറ്റിൽ രോഹിത് - റായിഡു സഖ്യം കൂട്ടിച്ചേർച്ച # റൺസാണ് ഇന്ത്യൻ ഇന്നിംഗ്സിന്റെ നട്ടെല്ല് .
എന്നെപ്പോലെ തന്നെ അവരും വിശന്നുകൊണ്ടായിരിക്കും ഉറങ്ങാൻ പോകുന്നത് എന്നെല്ലാം ഞാൻ ചിന്തിച്ചിരുന്നു .
ആറ് മുതൽ ഒൻപത് സീറ്റുകൾ വരെയുള്ള ഒരു ചെറിയ വിമാനം ചാർട്ടർ ചെയ്ത് പറക്കാൻ മണിക്കൂറിന് ഒന്നര ലക്ഷം മുതൽ രണ്ട് ലക്ഷം വരെയാണ് ഇപ്പോൾ ചെലവ് വരുന്നത് .
ഇതേ തുടർന്ന് ഡിജിപിയും മന്ത്രി കടകംപള്ളി സുരേന്ദ്രനും മാധ്യമങ്ങൾക്ക് വിലക്കില്ലെന്നും സുരക്ഷയൊരുക്കുന്നതിൻറെ ഭാഗമായ നടപടിമാത്രമാണ് നടക്കുന്നതെന്നും വിശദീകരിച്ചിരുന്നു .
```

**Comment by anoopkunchukuttan** [comment]
Hi Jerin,
yes, the provided corpus is tokenized. It is a bit tedious to now generate the original data. However, next release - we will release the untokenized corpus. You can use the de-tokenizer (linked provided on the page) to reconstruct the original corpus to a large extent. 

Do you observe any problems with the tokenization?

**Comment by jerinphilip** [comment]
I don't think a detokenizer would reverse all possible cases? The transformation is not invertible is it? Following being a counter-example:

* 2.8 => 2 . 8 -> 2.8
* January 2. 8 people => 2 . 8 => January 2.8 people.

I think it might be convenient to supply raw dataset and data-loaders which does the tokenization as a transform, than tokenized data release. (Just a suggestion). I also have certain cases where I have to train things on raw data - which might get tricky. For example, I want 2.8 to be 2.8 and not 2 . 8 while training Punkt for example.

**Comment by anoopkunchukuttan** [comment]
Hi Jerin, 
A new and larger version of the corpus is now available.  This is in untokenized form: https://indicnlp.ai4bharat.org
