### ISSUE TITLE
Cannot download datasets

### ISSUE THREAD

**Issue by Satyampd** [AI4Bharat/indicnlp_corpus#8]
I am trying to download datasets from IndicNLP, getting error from Google Storage API.

`<Error>
<Code>UserProjectAccountProblem</Code>
<Message>User project billing account not in good standing.</Message>
<Details>
The billing account for the owning project is disabled in state delinquent
</Details>
</Error>`

**Comment by bharat3012** [comment]
Similar Issue

**Comment by rosbal** [comment]
+1

**Comment by rosbal** [comment]
> +1

I was able to download datasets yesterday.

**Comment by anoopkunchukuttan** [comment]
The issue has been resolved, you should be able to download now. Please re-open if you run into any issues.

**Comment by sayanxtreme** [comment]
Hi Anoop. I wanted to download the Hindi corpus and I'm getting "User project billing account not in good standing." in xml

**Comment by srinath-zapr** [comment]
+1 I am also getting the same issue again.

**Comment by ashokurlana** [comment]
I am trying to download the [fastText embeddings](https://storage.googleapis.com/ai4bharat-public-indic-nlp-corpora/data/monolingual/indicnlp_v1/sentence/te.txt.gz) and getting the same issue.

**Comment by vmenan** [comment]
This is not working still
