### ISSUE TITLE
Is the OSCAR corpus contained in the Indicnlp corpus?

### ISSUE THREAD

**Issue by ibraheemmmoosa** [AI4Bharat/indicnlp_corpus#9]
It seemed to me after reading a line on the paper that this corpus includes the OSCAR corpus. Is it right?

**Comment by anoopkunchukuttan** [comment]
Yes, that is right

**Comment by ibraheemmmoosa** [comment]
Thanks for the clarification. I have one more question related to this. Is the version of OSCAR corpus included in Indic corpus unshuffled?
